version: '3.8'

services:
  ob-editor:
    build: .
    ports:
      - "3030:80"  # Map container port 80 to host port 3030
    networks:
      - ob-network

networks:
  ob-network:
    driver: bridge